docs/welcome.md

Ιnclude web and discord profile endpoints

---

masa/api/request.py
masa/api/validator_api.py
masa/miner/discord/all_guilds.py
masa/miner/discord/channel_messages.py
masa/miner/discord/guild_channels.py
masa/miner/discord/profile.py
masa/miner/discord/user_guilds.py
masa/miner/masa_protocol_request.py
masa/miner/twitter/followers.py
masa/types/discord.py
masa/validator/discord/all_guilds/forward.py
masa/validator/discord/all_guilds/parser.py
masa/validator/discord/all_guilds/reward.py
masa/validator/discord/channel_messages/forward.py
masa/validator/discord/channel_messages/parser.py
masa/validator/discord/channel_messages/reward.py
masa/validator/discord/guild_channels/forward.py
masa/validator/discord/guild_channels/parser.py
masa/validator/discord/guild_channels/reward.py
masa/validator/discord/profile/forward.py
masa/validator/discord/user_guilds/forward.py
masa/validator/discord/user_guilds/parser.py
masa/validator/discord/user_guilds/reward.py
masa/validator/forwarder.py
masa/validator/twitter/followers/forward.py
masa/validator/twitter/profile/forward.py
masa/validator/twitter/tweets/forward.py
neurons/miner.py
neurons/validator.py

- discord channel messages
- discord guild channels 
- discord user guilds
- discord guilds for discord workers.
closes #81

Add missing discord endpoints

---

masa/api/validator_api.py

- incredibly simple fix for correctly categorizing api endpoints (reported by user)

chore(docs): fixes api categories for web (reported by user)

---

masa/validator/forwarder.py

Checking if there is at least one response before setting scores

Avoiding setting scores when there are no responses

---

Makefile
docs/incentivized-testnet-event/1-create-environment.md
docs/incentivized-testnet-event/2-install-packages.md
docs/incentivized-testnet-event/3-create-wallets.md
docs/incentivized-testnet-event/4-fund-wallets.md
docs/incentivized-testnet-event/5-register-wallets.md
docs/incentivized-testnet-event/6-run-protocol.md
docs/incentivized-testnet-event/7-run-miner.md
docs/incentivized-testnet-event/intro.md

Add incentivized testnet docs

---

docs/incentivized-testnet-event/4-fund-wallets.md
docs/incentivized-testnet-event/5-register-wallets.md
docs/incentivized-testnet-event/6-run-protocol.md
docs/incentivized-testnet-event/7-run-miner.md
docs/incentivized-testnet-event/8-check-status.md
docs/incentivized-testnet-event/9-register.md
docs/incentivized-testnet-event/intro.md

- backfills docs based on devdocs update

fix(docs): testnet walkthrough copy

---

Makefile
healthcheck-dockerfile
healthcheck/main.py
masa/__init__.py
masa/api/validator_api.py
masa/base/healthcheck.py
masa/base/validator.py
masa/validator/forwarder.py
neurons/miner.py

- Adds some tooling to the validator and the miner to make sure they are actually running
- Cors configuration for the validator ( Enabling a browser to call the validator API )

feat: playground server and improvements

---

healthcheck/main.py

Added tempo and block times for easier understanding of registration periods

feat: calculating block times

---

.github/workflows/docker-publish.yml

This PR fixes #109 
With this PR, we're building and pushing the images upon release, regardless of whether there was a change in the code.

chore: debug publishing images

---

docs/RELEASE_NOTES.md

**Description:**
This PR is automated and orchestrated by the release workflow.  It updates the release notes in docs/RELEASE_NOTES.md every time a new release is published.  This automation ensures that our documentation is always up to date with the latest release notes, and links out to all previous release notes as well.  This bot makes the description of this PR just a little bit longer as to pass our CI checks!  I will write one more sentence to make the PR description longer
I will write one more sentence to make the PR description longer. I need to say just a bit more about this PR to pass the checks, but I'm fairly sure including this last sentence will do it! Kidding, this bot needs to write just a bit more to do it! Oh, how you've just gotta love CI and automation in general! …

chore: update release notes

---

.github/workflows/publish-release-notes.yml

This workflow pulls the latest release notes and automatically generates a PR to update the release notes file in our repository. Once the PR is reviewed and merged, the updated release notes are pushed to our documentation, ensuring that our users always have access to the most recent updates and changes.
This workflow pulls the latest release notes and automatically generates a PR to update the release notes file in our repository. Once the PR is reviewed and merged, the updated release notes are pushed to our documentation, ensuring that our users always have access to the most recent updates and changes.
This workflow pulls the latest release notes and automatically generates a PR to update the release notes file in our repository. Once the PR is reviewed and merged, …

fix: release trigger testing

---

.github/workflows/publish-release-notes.yml

This PR is automated and orchestrated by the release workflow. It updates the release notes in docs/RELEASE_NOTES.md every time a new release is published. This automation ensures that our documentation is always up to date with the latest release notes, and links out to all previous release notes as well. This bot makes the description of this PR just a little bit longer as to pass our CI checks! I will write one more sentence to make the PR description longer
I will write one more sentence to make the PR description longer. I need to say just a bit more about this PR to pass the checks, but I'm fairly sure including this last sentence will do it! Kidding, this bot needs to write just a bit more to do it! Oh, how you've just gotta love CI and automation in general! Let me …

fix: branch name

---

.github/workflows/publish-release-notes.yml

This PR is automated and orchestrated by the release workflow. It updates the release notes in docs/RELEASE_NOTES.md every time a new release is published. This automation ensures that our documentation is always up to date with the latest release notes, and links out to all previous release notes as well. This bot makes the description of this PR just a little bit longer as to pass our CI checks! I will write one more sentence to make the PR description longer
I will write one more sentence to make the PR description longer. I need to say just a bit more about this PR to pass the checks, but I'm fairly sure including this last sentence will do it! Kidding, this bot needs to write just a bit more to do it! Oh, how you've just gotta love CI and automation in general! Let me …

fix: workflow automation

---

masa/api/validator_api.py
masa/miner/web/scraper.py
masa/validator/discord/all_guilds/forward.py
masa/validator/discord/channel_messages/forward.py
masa/validator/discord/guild_channels/forward.py
masa/validator/discord/profile/forward.py
masa/validator/discord/user_guilds/forward.py
masa/validator/forwarder.py
masa/validator/twitter/followers/forward.py
masa/validator/twitter/profile/forward.py
masa/validator/twitter/tweets/forward.py
masa/validator/web/forward.py

Added limit field on each endpoint to limit responses sorted by score
This PR fixes #124 
Added limit param to required endpoints

feat: adding limit param to endpoints

---

.github/workflows/publish-release-notes.yml

This PR is automated and orchestrated by the release workflow. It updates the release notes in docs/RELEASE_NOTES.md every time a new release is published. This automation ensures that our documentation is always up to date with the latest release notes, and links out to all previous release notes as well. This bot makes the description of this PR just a little bit longer as to pass our CI checks! I will write one more sentence to make the PR description longer
I will write one more sentence to make the PR description longer. I need to say just a bit more about this PR to pass the checks, but I'm fairly sure including this last sentence will do it! Kidding, this bot needs to write just a bit more to do it! Oh, how you've just gotta love CI and automation in general! Let me …

fix: github workflow

---

Makefile
masa/__init__.py
masa/utils/uids.py
masa/validator/forwarder.py
requirements.txt

This PR bumps the version of the codebase for upcoming release.
In the context of Bittensor, bumping the code version is crucial for several reasons:
1. Compatibility: The version number must match the weights_version on the subnet. If they don't match, validators won't be able to set weights, and miners will receive warnings. This ensures that all nodes in the network are running compatible software versions, which is essential for network stability and functionality.
2. Version Control: Incrementing the version number helps in tracking changes and updates to the software. It provides a clear indication of the progression and improvements made over time.
3. Dependency Management: Other components or services that depend on this software can check the version number to …

chore: bump code version to 0.7.0 for release

---

README.md
docs/incentivized-testnet-event/4-fund-wallets.md
docs/incentivized-testnet-event/5-register-wallets.md
docs/incentivized-testnet-event/9-register.md

This PR updates the readme and relevant docs to hold us over until next week.  Adding dummy copy below to bypass our Ci checks.
I will write one more sentence to make the PR description longer. I need to say just a bit more about this PR to pass the checks, but I'm fairly sure including this last sentence will do it! Kidding, this bot needs to write just a bit more to do it! Oh, how you've just gotta love CI and automation in general! Let me say that sentence one more time: this bot needs to write more characters so that the we pass all of our checks!
I will write one more sentence to make the PR description longer. I need to say just a bit more about this PR to pass the checks, but I'm fairly sure including this last sentence will do it! Kidding, this bot needs to write …

chore: fixes readme

---

docs/miner/2-clone-repository.md
docs/validator/10-run-validator.md
docs/validator/2-clone-repository.md

This PR refactors our documentation to split into a miner and validator.
Bittensor is a decentralized network that leverages blockchain technology to create a scalable and secure infrastructure for AI. The network operates with two key roles: miners and validators.
Miners contribute AI models and computational power to the network, competing to provide the best solutions for processing data. They are rewarded in the network’s native token, TAO, based on the quality of their contributions. Unlike traditional mining, Bittensor mining focuses on the quality of AI computations.
Validators maintain the integrity of the blockchain by verifying transactions and ensuring the accuracy of miners’ computations. They help reach consensus and are rewarded with TAO tokens for their role …

fix: doc copy

---

README.md

Fixes docs url, changed from https://developers.masa.ai/docs/masa-subnet/setup/intro to https://developers.masa.ai/docs/masa-subnet/welcome

feat: updating readme

---

.github/workflows/publish-release-notes.yml

This PR introduces a new GitHub workflow that automates the process of generating and updating release notes for our repository. By leveraging GitHub Actions, we can now automatically create release notes based on the commit history, pull requests, and other relevant metadata whenever a new release is created.
This PR introduces a new GitHub workflow that automates the process of generating and updating release notes for our repository. By leveraging GitHub Actions, we can now automatically create release notes based on the commit history, pull requests, and other relevant metadata whenever a new release is created.

fix: release notes title

---

docs/miner/0-intro.md
docs/miner/6-run-protocol.md
docs/validator/8-run-protocol.md
docs/validator/9-edit-env.md

This PR improves Usability and Understanding: Clear, up-to-date documentation helps users and contributors understand the purpose, functionality, and setup of your project. It reduces confusion and the learning curve, making it easier for others to get started quickly.  Ensures Accuracy: As code evolves, new features, bug fixes, and other changes may alter how the software works. Outdated documentation can lead to misunderstandings or misuse of the software. Regular updates ensure that documentation accurately reflects the current state of the project.  Boosts Collaboration: Open source projects thrive on collaboration. Well-maintained documentation encourages contributions by providing clear guidelines on how others can get involved, report issues, or suggest …

fix: docs copy

---

Makefile
environment.yml
masa/__init__.py
masa/base/neuron.py
masa/base/validator.py
masa/validator/forwarder.py
requirements.txt

This PR fixes #255 
Here's a summary of the changes made in the diff:
- Updated the version from `0.8.0` to `1.0.0`.
```python:masa/__init__.py
-__version__ = "0.8.0"
+__version__ = "1.0.0"
```
- Imported `Config` from `bittensor_wallet`.
- Modified the wallet configuration to use `wallet_specific_config`.
```python:masa/base/neuron.py
+from bittensor_wallet import Config
// ... existing code ...
+            wallet_specific_config = Config(
+                hotkey=self.config.wallet.hotkey,
+                name=self.config.wallet.name,
+                path=self.config.wallet.path,
+            )
+            self.wallet = bt.wallet(config=wallet_specific_config)
```
- Removed the processing of raw weights to final weights via subtensor limitations.
- Simplified the …

feat: adding new wallet config for latests sdk

---

masa/__init__.py
pyproject.toml

This PR bumps versioning for the hotfix release that fixes port mappings so folks can run multiple validators and miners.  Repeating this text to pass CI!
This PR bumps versioning for the hotfix release that fixes port mappings so folks can run multiple validators and miners.  Repeating this text to pass CI!
This PR bumps versioning for the hotfix release that fixes port mappings so folks can run multiple validators and miners.  Repeating this text to pass CI!
This PR bumps versioning for the hotfix release that fixes port mappings so folks can run multiple validators and miners.  Repeating this text to pass CI!
This PR bumps versioning for the hotfix release that fixes port mappings so folks can run multiple validators and miners.  Repeating this text to pass CI! …

fix: version bump for hotfix release

---

.github/ISSUE_TEMPLATE/Spike

Spike ticket template
This PR fixes #

chore: add spike template

---

.github/workflows/coverage.yml

This PR fixes broken tests that needed miner and validator wallets to use that are already registered to the subnet. 
I've added these as secrets for the repo, and made several other adjustments to ensure the dependencies for testing are met.

fix: Fix tests by adding registered miner and validator wallets as secrets, among other things

---

masa/validator/forwarder.py

This pull request updates the `masa/validator/forwarder.py` file to improve the handling of tweet IDs by expanding the range of zero characters that are stripped from the beginning of these IDs. This enhancement ensures that tweet IDs are processed correctly across various numeral systems.
- **Regex Update**: The regular expression used to remove leading zeros from tweet IDs has been updated. The new regex pattern now includes zero characters from multiple numeral systems, such as:
- Arabic (٠)
- Devanagari (०)
- Bengali (০)
- Gujarati (૦)
- Tamil (௦)
- Telugu (౦)
- Kannada (೦)
- Malayalam (൦)
- Thai (๐)
- Lao (໐)
- Tibetan (༠)
- Myanmar (၀)
- Khmer (០)
- **Code Context**: The changes are implemented in the `get_miners_volumes` method, which processes miner responses to extract and …

fix: all leading zeros exploit

---

Makefile
README.md
masa/base/validator.py
masa/validator/forwarder.py

This PR introduces several key improvements to enhance user experience and code maintainability:
1. **📚 Documentation Enhancements**
- Comprehensive README updates with clear setup instructions
- Detailed sections for both Subnet 42 and 59
- Added TaoStats monitoring information
- Improved wallet setup and registration guidance
2. **⚙️ Makefile Improvements**
- Simplified network selection using `NETWORK=test|main` flag
- Eliminated need to comment/uncomment for network switching
- More intuitive command structure
- Better documentation of available commands
3. **🔧 Code Quality**
- Enhanced weight setting log messages for better clarity
- Improved debug information for validators
- More consistent logging format
- Verified all Makefile commands work with both networks
- Tested …

docs: Enhanced Documentation Build System and Logging
