masa-finance/masa-bittensor

- Makefile
- docs/advanced/blacklisting.md
- masa/base/miner.py
- masa/base/neuron.py
- masa/utils/config.py
- neurons/miner.py
- neurons/validator.py
- using #64 and #88 implements basic blacklist functionality as described in #89
- adds logs to display blacklisting reasons, vpermit status, and stake size
- saves and loads state related to storing neurons with min stake required (by hotkey)
- checks stake size per hotkey every 1 tempo to ensure we aren't checking stakes on every request
- resolves console warning in miner about allowing any requests through
- updates docs in `docs/advanced/blacklisting`
- validator with enough stake:
- validator blacklisted:
TODO
(answer is in #88)
> feat: implements basic miner blacklist using vpermit and min stake req

- .github/release.yml
Closes #83 .
It adds the configuration for github automated release notes generation from the labels in the PRs
> ci(release): add release configuration

- .github/workflows/commitlint.yml
This forces to have commits following the conventional commit structure by gating PRs.
In scope of #83
> ci: add commitlint workflow

- masa/utils/uids.py
- masa/validator/forwarder.py
- tests/test_template_validator.py
- Closes #92
Implementation heavily inspired by SN 15 - Blockchain Insight's own implementation of miner selection function ([link](https://github.com/blockchain-insights/blockchain-data-subnet/blob/c6b8d4e7e9607d0f5ed2bac24857ab1f11cf56fb/neurons/validators/utils/uids.py#L41))
Setup:
- Local Validator on port 8091
- Local Miner on port 8092
- Using local Oracle instance (via code) 
- Local Oracle node on port 8080
Local version control:
- Rebased branch (different name to assert changes)
- Local changes
- Change Oracle Base URL
| <img src='https://github.com/masa-finance/masa-bittensor/assets/21087992/39a6d456-aa90-47a1-8638-22e30d1452c1' width='400'> |
| :--: |
| _Recent Tweets_ | _Profile_ | _Followers_ |
| :--: | :--: | :--: |
| <img width="583" alt="image" …
> feat: implement basic sanitation for miner selection

- .github/workflows/commitlint.yml
We want to only gate PRs in any case - no need to run the linter on branches
> ci: run commitlint checks only on PRs

- .github/workflows/docker-publish.yml
This PR enhances the existing GitHub Actions workflow to build and publish Docker images with a tag corresponding to the release version whenever a new release is published. This ensures that Docker images are consistently tagged with the release version, improving traceability and version management.
1. Trigger Workflow on Release:
- Updated the on section to include the release event with the published type. This triggers the workflow whenever a new release is published.
2. Use Release Tag for Docker Images:
- Modified the Build and push image step to use the release tag (github.event.release.tag_name) as the Docker image tag if the event is a release. Otherwise, it defaults to the branch name.
3. Display Image Tags:
- Updated the display-tags job to show the correct image tags based on …
> feat: publish tagged images on release

- requirements.txt
This PR fixes #144.  It adds to the `requirements.txt` file to specify exact versions for project dependencies:
- bittensor==7.1.0
- loguru==0.7.2
- python-dotenv==0.21.0
- torch==2.3.0
- watchfiles==0.22.0
1. **Consistency**: Ensures all environments use the same dependency versions.
2. **Reproducibility**: Enables consistent builds and behavior across different setups.
3. **Stability**: Prevents breaking changes from newer versions, maintaining project stability.
1. **Deterministic Builds**: Guarantees the same set of dependencies is installed every time.
2. **Controlled Upgrades**: Allows systematic testing before upgrading to newer versions.
3. **Conflict Avoidance**: Reduces risk of dependency conflicts.
None
**[Signed …
> fix: adds versions to requirements.txt

- .github/workflows/publish-release-notes.yml
This PR fixes the issue where release workflows were also including pushes to the main branch.  We only need it to be on releases!
This PR fixes the issue where release workflows were also including pushes to the main branch.  We only need it to be on releases!
This PR fixes the issue where release workflows were also including pushes to the main branch.  We only need it to be on releases!
This PR fixes the issue where release workflows were also including pushes to the main branch.  We only need it to be on releases!
This PR fixes the issue where release workflows were also including pushes to the main branch.  We only need it to be on releases!
This PR fixes the issue where release workflows were also including pushes to the main branch.  We only need it to be on …
> fix: release notes only on release

- .github/workflows/publish-release-notes.yml
This PR is automated and orchestrated by the release workflow. It updates the release notes in docs/RELEASE_NOTES.md every time a new release is published. This automation ensures that our documentation is always up to date with the latest release notes, and links out to all previous release notes as well. This bot makes the description of this PR just a little bit longer as to pass our CI checks! I will write one more sentence to make the PR description longer
I will write one more sentence to make the PR description longer. I need to say just a bit more about this PR to pass the checks, but I'm fairly sure including this last sentence will do it! Kidding, this bot needs to write just a bit more to do it! Oh, how you've just gotta love CI and automation in general! Let me …
> fix:  automatic pr creator

- masa/base/miner.py
- masa/base/neuron.py
- masa/base/validator.py
- masa/utils/config.py
This PR introduces an auto-update feature for the `BaseNeuron`, `BaseMinerNeuron`, and `BaseValidatorNeuron` classes. The feature periodically checks for updates from the GitHub repository and updates the local code if a new release is found. Additionally, it adds a new configuration option to enable or disable this auto-update functionality.
1. **New Dependencies**:
- Added `subprocess` and `requests` imports to handle update checks and execution.
2. **BaseNeuron Class**:
- Added `auto_update` method to check for the latest release on GitHub and update the local repository if necessary.
3. **BaseMinerNeuron Class**:
- Introduced `auto_update_thread` to handle auto-updates in a separate thread.
- Added `run_auto_update` and `run_auto_update_in_loop` methods to periodically check for …
> feat: auto update

- Makefile
- masa/base/miner.py
- masa/base/neuron.py
- masa/base/validator.py
- neurons/validator.py
- requirements.txt
This pull request implements a change in how we manage versioning and updates within the Bittensor project. We are transitioning from using commit hashes to Git tags for the following reasons:
1. **Clarity and Readability**:
- **Git Tags**: Tags provide a human-readable versioning system (e.g., `v3.4.0`), making it easier to identify and reference specific releases.
- **Commit Hashes**: Previously, we relied on commit hashes, which are less intuitive and harder to track for specific versions.
2. **Consistency with Releases**:
- **Git Tags**: Tags are directly associated with releases on GitHub, ensuring that each release corresponds to a specific, immutable point in the repository's history.
- **Commit Hashes**: Using commit hashes could lead to inconsistencies, as they …
> fix: auto-update

- masa/base/miner.py
- masa/base/validator.py
- pyproject.toml
After release, noticed a bug on mainnet where the ports were not being correctly mapped to the axon, even though the Makefile was passing `--axon.port` correctly.  The likely culprit is/was an upgrade to bittensor, and the bug was not caught until running multiple axons on mainnet.
Updated code for the miner and validator base:
```
self.axon = bt.axon(
wallet=self.wallet, config=self.config, port=self.config.axon.port
)
```
By explicitly passing an axon port, we resolve the issue where an axon is trying to be served by the default ports, `0891` for miners and `0892` for validators.
> fix: maps axon ports correctly

- Makefile
- masa/__init__.py
- masa/base/neuron.py
- masa/base/validator.py
- masa/utils/weights.py
- pyproject.toml
This PR upgrades to Bittensor 8.2.0 and in the process solves a few bug fixes that were present when doing so, namely changes to the code that supported Bittensor 8.1.1
- Removes the special wallet Config in `masa/base/neuron.py` in favor of passing `self.config` directly to the wallet.
- Ports the `process_weights_for_netuid` function from the Bittensor library into the codebase for refined control / ensuring that weights can be set at all times.
- Adds `weights.py` file to `masa/utils` to support comment above
- Bumps package version in our `pyproject.toml`
> fix: upgrade to bittensor 8.2.0

- masa/utils/weights.py
This PR fixes this issue with validators sometimes not being able to set weights.  The issue was traced down to logging bugs in the Bittensor library.
Sometimes the library was calling `bt.logging.info("Weights", weights)`, where it needs to be `bt.logging.info("Weights", *weights)`.
The resolve has been to copy the relevant logic into the subnet code, and comment out the logging bugs.
After testing on testnet, validators are able to set weights even if no scores have been marked.
> fix: setting weights

- Makefile
- masa/api/server.py
- masa/base/validator.py
- masa/validator/forwarder.py
This PR fixes #299 and stores tweets by uid, to ensure that each miner is only being scored on unique tweets each turn.  We wipe the state when a UID is ever deregistered (determined by resync_metagraph()).
There were also updates to indexing tweets, so we just store by query and unique tweet.  This makes it easier for us to index the data in a future, central service.  Typing this again to pass CI!
This PR fixes #299 and stores tweets by uid, to ensure that each miner is only being scored on unique tweets each turn.  We wipe the state when a UID is ever deregistered (determined by resync_metagraph()).
There were also updates to indexing tweets, so we just store by query and unique tweet.  This makes it easier for us to index the data in a future, central service.  Typing …
> feat: tweets by UID (miner)

- Makefile
- masa/api/server.py
- masa/base/validator.py
- masa/utils/uids.py
- masa/validator/forwarder.py
- masa/validator/scorer.py
This PR fixes #300 and reduces randomness in how validators select miners for scoring, and the keyword that they use.
Validators now keep a set of "uncalled uids", specifically used for volume scoring.  When this set of uncalled uids reaches 0, we establish a new query (from the list of trending queries), and reset the set to version-checked uids from the metagraph.
This new logic ensures that per validator, miners are scored fairly, by exhausting the miners in the metagraph before re-calling any UID, and by keeping the query / keyword consistent through each iteration of the list.
Other aspects of the code were cleaned up, like keeping volume tracking to only the last 6 tempos, and removing miner versioning from state, as we do not need it to persist.
**Notes for …
> feat: reduce randomness

- masa/__init__.py
- masa/validator/forwarder.py
Malicious miners were padding their tweet id's with zeros, passing our validation logic and scoring uniquely in our algorithm.  This PR fixes said issue in the following ways:
- **File:** `masa/__init__.py`
- **Change:** The version of the code has been updated from `1.2.0` to `1.3.0`.
- **Impact:** This version bump indicates a new release with potentially new features, improvements, or bug fixes. It is crucial for ensuring compatibility with the subnet's `weights_version`.
- **File:** `masa/validator/forwarder.py`
- **Class:** `Forwarder`
- **Change:** 
- The logic for handling tweet response IDs has been updated to remove leading zeros.
- The `unique_tweets_response` now uses IDs stripped of leading zeros as dictionary keys.
- Additionally, the `Tweet` object within …
> fix(scoring): padded zeros

- masa/validator/forwarder.py
The validator was showing success messages and adding volume scores prematurely, before all validation checks were complete. This could lead to:
1. Confusing logs showing both PASS and FAIL for the same batch
2. Potential incorrect volume scoring for invalid tweets
3. Misleading validation status reporting
- Moved success logging to only appear after ALL validation checks have passed
- Previously we were showing "PASSED - X valid tweets" before completing validation
- Now success messages only appear if all validation steps pass:
- Basic tweet structure validation
- Tweet ID validation
- Duplicate checks within batch
- Query match validation
- Timestamp validation
- Historical duplicate checking
- Moved ALL volume-related logic inside the `all_tweets_valid` block
- Volume is now only …
> fix: Validation Logic and Clean Up Logging

- masa/base/neuron.py
- pyproject.toml
This PR addresses a version mismatch between our git tags and package version:
- Git tag was at v1.5.2
- But pyproject.yaml still specified 1.5.0
- This caused running validators to report spec_version 150 instead of 152
Additionally, this PR improves version logging to make it clearer what version is running:
🟢 Code is up to date! Current: 153 (v1.5.3), Required: 150
1. We will soon update subnet hyperparameters to require version 1.5.2 (spec_version 152)
2. Without this fix, validators would continue reporting version 1.5.0 (spec_version 150)
3. This would cause all validators to fail setting weights once the requirement changes
- Update version in pyproject.yaml to 1.5.3
- Improve version logging to show both current and required versions
- Ensure consistent version reporting across …
> fix: set version 1.5.3 in pyproject.yaml

- masa/__init__.py
- masa/base/neuron.py
- pyproject.toml
v1.5.3 had a small issue with logging the version incorrectly, but also had a larger issue with the version reference not being a single source of truth.
previously, to release a new version, one would need to update the version in the pyproject.yaml file, the __init__.py file, and the release notes.
Now, to release a new version, one only needs to update the version in the pyproject.yaml file.
This version bumps up to 1.5.4, and will correctly log the current and required versions at init.
```
🟢 Code is up to date! Current: 154 (v1.5.4), Required: 154
```
or, if not up to date:
🟡 Code is outdated! Current: 153, Required: 154. Please update your code to the latest release!
- Update version in pyproject.yaml to 1.5.4
- Uses a single source of truth for the version in __init__.py (only set …
> fix: incorrect log line, single source of truth for version number (pyproject.toml)
